services:
  - type: web
    name: tracker-server
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: TIDB_URL
        sync: false
      - key: TIDB_USER
        sync: false
      - key: TIDB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        sync: false
      - key: ADMIN_BOOTSTRAP_USERNAME
        sync: false
      - key: ADMIN_BOOTSTRAP_PASSWORD
        sync: false
